### ISSUE TITLE
代码求助

### ISSUE THREAD

**Issue by 18sym** [meng1103/Federated-Learning-Non-IID#3]
为什么会出现：
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from models.Clients import ClientUpdate
ModuleNotFoundError: No module named 'models'
显示找不到啊

**Comment by windwindwa** [comment]
找不到 models 包。 
你用的pycharm 运行的吗？

可以自查一下， https://blog.csdn.net/GungnirsPledge/article/details/107586458

**Comment by 18sym** [comment]
我上传到服务器运行的，结果刚才一看没有init.py,结果上传之后，还是不行。

**Comment by windwindwa** [comment]
> 我上传到服务器运行的，结果刚才一看没有init.py,结果上传之后，还是不行。

shell方式运行的吗？  
你截个图吧。截带有 main.py和models文件夹  的

**Comment by 18sym** [comment]
好的，
![image](https://github.com/meng1103/Federated-Learning-Non-IID/assets/104238479/273598b3-3654-4542-9a2a-17ab6d0bd964)
![image](https://github.com/meng1103/Federated-Learning-Non-IID/assets/104238479/9cafa8f4-ed36-4df2-a793-c859f59c7ba9)
![image](https://github.com/meng1103/Federated-Learning-Non-IID/assets/104238479/e0ed3005-4d1d-4833-95d3-1e1b978edcb7)
，然后我的环境是
![image](https://github.com/meng1103/Federated-Learning-Non-IID/assets/104238479/2520f58c-ef46-4a97-b5a6-3aa2fa2a0f7a)

**Comment by windwindwa** [comment]
> 好的，
> 
> ![image](https://github.com/meng1103/Federated-Learning-Non-IID/assets/104238479/273598b3-3654-4542-9a2a-17ab6d0bd964)
> 
> ![image](https://github.com/meng1103/Federated-Learning-Non-IID/assets/104238479/9cafa8f4-ed36-4df2-a793-c859f59c7ba9)
> 
> ![image](https://github.com/meng1103/Federated-Learning-Non-IID/assets/104238479/e0ed3005-4d1d-4833-95d3-1e1b978edcb7)
> 
> ，然后我的环境是
> 
> ![image](https://github.com/meng1103/Federated-Learning-Non-IID/assets/104238479/2520f58c-ef46-4a97-b5a6-3aa2fa2a0f7a)
> 
> 

两个选择解决这个问题 
1. 将main.py移动到和models目录一个层级
2. 将main.py中关于from models.aaa imprt bbb。 去掉models.  变为from aaa improt bbb

这个问题正常在pycharm等工具下是没有的，ide智能解决了。但是你是使用命令行，然后这个路径还没有被python索引导致的

**Comment by 18sym** [comment]
第二种方法不太行
![image](https://github.com/meng1103/Federated-Learning-Non-IID/assets/104238479/b26cfd9f-8127-4af6-9dca-71c6b5627872)
,第一种好像也不行
![image](https://github.com/meng1103/Federated-Learning-Non-IID/assets/104238479/19f39ef0-8a88-4e9e-8360-e67ebac9a4bf)
就是检索不到，昨天晚上尝试添加路径也没有办法。

**Comment by windwindwa** [comment]
> 第二种方法不太行
> 
> ![image](https://github.com/meng1103/Federated-Learning-Non-IID/assets/104238479/b26cfd9f-8127-4af6-9dca-71c6b5627872)
> 
> ,第一种好像也不行
> 
> ![image](https://github.com/meng1103/Federated-Learning-Non-IID/assets/104238479/19f39ef0-8a88-4e9e-8360-e67ebac9a4bf)
> 
> 就是检索不到，昨天晚上尝试添加路径也没有办法。

第一个报错已经解决了。
新的报错和上一个问题是一样的。

**Comment by 18sym** [comment]
第一个报错，不还是找不到Client.py，那里面的函数方法也没办法用啊
